"""Offline fixture cases for the four CloudTrail rules."""

from __future__ import annotations

from tests.builders import cloudtrail_state, trail

from . import Case, Expected

CASES = (
    Case(
        case_id="ct-healthy-trail",
        service="cloudtrail",
        category="clean",
        covers=("CT-001", "CT-002", "CT-003", "CT-004"),
        description="A multi-region, validating, logging trail produces nothing.",
        data=cloudtrail_state(trail()),
    ),
    Case(
        case_id="ct-001-no-trails",
        service="cloudtrail",
        category="vulnerable",
        covers=("CT-001",),
        description="DescribeTrails returning an empty list is HIGH.",
        data=cloudtrail_state(),
        expected=(Expected("CT-001", "aws-account", "HIGH"),),
    ),
    Case(
        case_id="ct-001-trails-unreadable",
        service="cloudtrail",
        category="edge",
        covers=("CT-001", "CT-002"),
        description="A denied DescribeTrails must never be reported as 'no trail exists'.",
        data=cloudtrail_state(readable=False),
    ),
    Case(
        case_id="ct-002-single-region-only",
        service="cloudtrail",
        category="vulnerable",
        covers=("CT-002",),
        description="A lone single-region trail is MEDIUM at the account level.",
        data=cloudtrail_state(trail(multi_region=False)),
        expected=(Expected("CT-002", "aws-account", "MEDIUM"),),
    ),
    Case(
        case_id="ct-002-two-single-region-trails-one-finding",
        service="cloudtrail",
        category="edge",
        covers=("CT-002",),
        description="Two single-region trails are one account-level finding, not two.",
        data=cloudtrail_state(trail("a", multi_region=False), trail("b", multi_region=False)),
        expected=(Expected("CT-002", "aws-account", "MEDIUM"),),
    ),
    Case(
        case_id="ct-002-one-multi-region-suffices",
        service="cloudtrail",
        category="edge",
        covers=("CT-002",),
        description="A single multi-region trail satisfies the rule even alongside regional ones.",
        data=cloudtrail_state(trail("regional", multi_region=False), trail("global", multi_region=True)),
    ),
    Case(
        case_id="ct-003-validation-disabled",
        service="cloudtrail",
        category="vulnerable",
        covers=("CT-003",),
        description="Log file validation disabled is MEDIUM, per trail.",
        data=cloudtrail_state(trail(log_validation=False)),
        expected=(Expected("CT-003", "management-trail", "MEDIUM"),),
    ),
    Case(
        case_id="ct-003-per-trail-attribution",
        service="cloudtrail",
        category="multi",
        covers=("CT-003",),
        description="Only the trail with validation off is reported, named by trail.",
        data=cloudtrail_state(trail("good", log_validation=True), trail("bad", log_validation=False)),
        expected=(Expected("CT-003", "bad", "MEDIUM"),),
    ),
    Case(
        case_id="ct-004-stopped-trail",
        service="cloudtrail",
        category="vulnerable",
        covers=("CT-004",),
        description="A configured trail with logging stopped is HIGH.",
        data=cloudtrail_state(trail(is_logging=False)),
        expected=(Expected("CT-004", "management-trail", "HIGH"),),
    ),
    Case(
        case_id="ct-004-delivery-error",
        service="cloudtrail",
        category="vulnerable",
        covers=("CT-004",),
        description="A logging trail reporting a delivery error is HIGH: enabled but not delivering.",
        data=cloudtrail_state(trail(delivery_error="AccessDenied writing to the destination bucket")),
        expected=(Expected("CT-004", "management-trail", "HIGH"),),
    ),
    Case(
        case_id="ct-004-empty-delivery-error-string",
        service="cloudtrail",
        category="malformed",
        covers=("CT-004",),
        description="An empty-string delivery error means 'no error yet' and must not fire.",
        data=cloudtrail_state(trail(delivery_error="")),
    ),
    Case(
        case_id="ct-004-status-unknown",
        service="cloudtrail",
        category="edge",
        covers=("CT-004",),
        description="Denied GetTrailStatus leaves logging state unknown, so the rule stays silent.",
        data=cloudtrail_state(trail(is_logging=None)),
    ),
    Case(
        case_id="ct-004-stopped-trail-still-reports-validation",
        service="cloudtrail",
        category="multi",
        covers=("CT-002", "CT-003", "CT-004"),
        description="A stopped, single-region, non-validating trail produces all three findings at once.",
        data=cloudtrail_state(trail("neglected", multi_region=False, log_validation=False, is_logging=False)),
        expected=(
            Expected("CT-002", "aws-account", "MEDIUM"),
            Expected("CT-003", "neglected", "MEDIUM"),
            Expected("CT-004", "neglected", "HIGH"),
        ),
    ),
    Case(
        case_id="ct-multiple-trails-mixed-health",
        service="cloudtrail",
        category="multi",
        covers=("CT-003", "CT-004"),
        description="Across three trails, each per-trail rule fires only on the trails that fail it.",
        data=cloudtrail_state(
            trail("healthy", multi_region=True),
            trail("unvalidated", log_validation=False),
            trail("stopped", is_logging=False),
        ),
        expected=(
            Expected("CT-003", "unvalidated", "MEDIUM"),
            Expected("CT-004", "stopped", "HIGH"),
        ),
    ),
    Case(
        case_id="ct-missing-optional-fields",
        service="cloudtrail",
        category="malformed",
        covers=("CT-002", "CT-003"),
        description="A trail dict with only a name defaults to non-multi-region and non-validating.",
        data={"trails": [{"name": "bare"}], "trails_readable": True},
        expected=(
            Expected("CT-002", "aws-account", "MEDIUM"),
            Expected("CT-003", "bare", "MEDIUM"),
        ),
    ),
)
