"""Render docs/cis-mapping.md from compliance/cis_mapping.json.

The JSON file is the source of truth; the prose is generated so the two cannot
disagree. Run after editing the mapping:

    python scripts/render_cis_doc.py
"""

from __future__ import annotations

import json
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(REPO_ROOT, "compliance", "cis_mapping.json")
TARGET = os.path.join(REPO_ROOT, "docs", "cis-mapping.md")

NOT_CLAIMED = """## Not claimed

The benchmark contains controls this tool does not implement, and the mapping
does not pretend otherwise. Notable gaps, all requiring APIs the auditor does
not call: root-account MFA and root access keys (1.4-1.6), the IAM password
policy (1.8-1.9), IAM Access Analyzer (1.20), MFA Delete on S3 buckets (2.1.2),
AWS Config (3.3), CloudTrail log encryption with a customer-managed key (3.5),
and the whole of the monitoring and networking sections.

Adding a rule for any of these means adding its read permission to
`auditor/permissions.py`, which regenerates the IAM policy — the reason the
scope is deliberate rather than accidental."""


def render(document) -> str:
    benchmark = document["benchmark"]
    mapped = [r for r in document["rules"] if r["status"] == "mapped"]

    lines = [
        "# CIS AWS Foundations Benchmark mapping",
        "",
        "<!-- Generated by scripts/render_cis_doc.py from compliance/cis_mapping.json. -->",
        "",
        f"**Benchmark:** {benchmark['name']} **v{benchmark['version']}** ({benchmark['published']})",
        "",
        benchmark["note"],
        "",
        "## Counting rule",
        "",
        document["counting_rule"],
        "",
        "| Status | Meaning | Count |",
        "| ------ | ------- | ----: |",
    ]
    for key in ("mapped", "partial", "unmapped"):
        count = sum(1 for r in document["rules"] if r["status"] == key)
        lines.append(f"| `{key}` | {document['status_definitions'][key]} | {count} |")

    lines += [
        "",
        f"**Headline metric: {len(mapped)} of {len(document['rules'])} rules have a "
        "direct, defensible CIS mapping.**",
        "",
        "The two `partial` entries are deliberately excluded. They share a control's",
        "rationale but not its audit condition, and counting them would take the figure",
        "to 13/14 on the strength of an argument that would not survive review.",
        "",
        "## Mapped rules",
        "",
        "| Rule | CIS control | Control title |",
        "| ---- | ----------- | ------------- |",
    ]
    for rule in mapped:
        lines.append(f"| `{rule['rule_id']}` | **{rule['control_id']}** | {rule['control_title']} |")

    lines += ["", "## Rationale for each mapping", ""]
    for rule in document["rules"]:
        control = (
            f"CIS {rule['control_id']} — {rule['control_title']}"
            if rule["control_id"]
            else "No mapped control"
        )
        lines += [
            f"### `{rule['rule_id']}` — {rule['status']}",
            "",
            f"*Finding:* {rule['finding']}",
            "",
            f"*Control:* {control}",
            "",
            rule["rationale"],
            "",
        ]

    lines.append(NOT_CLAIMED)
    return "\n".join(lines) + "\n"


def main() -> int:
    with open(SOURCE, encoding="utf-8") as handle:
        document = json.load(handle)
    with open(TARGET, "w", encoding="utf-8") as handle:
        handle.write(render(document))
    print(f"Wrote {os.path.relpath(TARGET, REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
